name: Convert Markdown to PDF

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Pandoc and LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex texlive-luatex texlive-lang-cjk fonts-noto-cjk

    - name: Convert Markdown to PDF
      run: |
        for file in APIM_UserGuide/*.md; do
          [ -f "$file" ] || continue
          pandoc "$file" -o "${file%.md}.pdf" --pdf-engine=xelatex -V mainfont="Noto Sans CJK KR"
        done

    - name: Commit and Push converted PDF files
      run: |
        git config --local user.name "pmmms1226@gmail.com"
        git config --local user.email "pmmms1226@gmail.com"
        git add *.pdf
        git commit -m "Convert Markdown to PDF"
        git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/cloudz-mp/apim-user-guide.git HEAD:main
      env:
        ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
